menus/urls.py
from django.conf.urls import url
from .views import(
	ItemListView,
	ItemDetailView,
	ItemCreateView,
	ItemUpdateView,

)

urlpatterns= [

url(r'^create/$', ItemCreateView.as_view(),name='create'),
#url(r'^(?P<pk>\d+)/edit/$',ItemUpdateView.as_view(),name='update'),
url(r'^(?P<pk>\d+)/$',ItemUpdateView.as_view(),name='detail'),
url(r'^$',ItemListView.as_view(),name='list'),



]

muipicky/urls.py
from django.conf.urls import url,include
from profiles.views import ProfileToggle,RegisterView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import views as auth_views
from menus.views import HomeView
from django.contrib import admin
from restaurants.views import RestaurantList,RestaurantCreateView,RestaurantUpdateView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(),name='home'),
    url(r'^About/$', TemplateView.as_view(template_name='About.html'),name='about'),
    url(r'^restaurants/$',RestaurantList.as_view(),name='restaurants'),
    url(r'^items/',include('menus.urls',namespace='menus')),
    url(r'^u/',include('profiles.urls',namespace='profiles')),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^profile-follow/$',ProfileToggle.as_view(),name='follow'),
    url(r'^password-reset/$', auth_views.password_reset,name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done,name='password_reset_done'),
    url(r'^password-reset/complete/$',auth_views.password_reset_complete,name='password_reset_complete'),
    url(r'^password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$',auth_views.password_reset_confirm,name='password_reset_confirm'),
    url(r'^restaurants/create/$', RestaurantCreateView.as_view(),name='restaurants-create'),
    url(r'^restaurants/(?P<slug>[\w-]+)/$',RestaurantUpdateView.as_view(),name='detail'),
    #url(r'^restaurants/(?P<slug>[\w-]+)/edit/$',RestaurantUpdateView.as_view(),name='edit'),
  #  url(r'^restaurants/moga/$',MogaRestaurants.as_view()),
    url(r'^Contact/$', TemplateView.as_view(template_name='Contact.html'),name='contact'),
]

menus/models.py
from django.db import models
from django.conf import settings
from restaurants.models import RestaurantLocation
from django.urls import reverse

class Item(models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	restaurants=models.ForeignKey(RestaurantLocation, on_delete=models.CASCADE)
	name=models.CharField(max_length=120)
	contents=models.TextField(help_text='separate each item by comma')
	excludes=models.TextField(blank=True,null=True,help_text='separate each item by comma')
	public=models.BooleanField(default=True)
	timestamp=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name 

	def get_absolute_url(self):
		return reverse('menus:detail',kwargs={'pk':self.pk})

	class Meta:
		ordering=['-updated','-timestamp'] 
	def get_contents(self):
		return self.contents.split(',')
	def get_excludes(self):
		return self.excludes.split(',')
	

# Create your models here.

menus/forms.py
from django import forms
from .models import Item
from restaurants.models import RestaurantLocation

class ItemForm(forms.ModelForm):
	class Meta:
		model=Item
		fields=[
		'restaurants',
		'name',
		'contents',
		'excludes',
		'public',
	
		]
	def __init__(self,user=None,*args,**kwargs):
		super(ItemForm,self).__init__(*args,**kwargs)
		self.fields['restaurants'].queryset=RestaurantLocation.objects.filter(owner=user)

menus/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView,DetailView,CreateView,UpdateView,View
from .models import Item
from .forms import ItemForm

class HomeView(View):
	def get(self,request,*args,**kwargs):
		if not request.user.is_authenticated():
			return render(request,'home.html',{})
		user=request.user
		is_following_user_ids=[x.user.id for x in user.is_following.all()]
		qs=Item.objects.filter(user__id__in=is_following_user_ids,public=True)
		return render(request,'menus/home-feed.html',{"object_list":qs})


class ItemListView(LoginRequiredMixin,ListView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

class ItemDetailView(DetailView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin,CreateView):
	form_class=ItemForm
	template_name='form.html'
	def form_valid(self,form):
		obj=form.save(commit=False)
		obj.user=self.request.user
		return super(ItemCreateView,self).form_valid(form)

	def get_form_kwargs(self):
		kwargs=super(ItemCreateView,self).get_form_kwargs()
		kwargs['user']=self.request.user
		return kwargs

	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)
	def get_context_data(self,*args,**kwargs):
		return super(ItemCreateView,self).get_context_data(*args,**kwargs)
		context['title']='Create Item'
		return context

class ItemUpdateView(LoginRequiredMixin,UpdateView):
	form_class=ItemForm
	template_name='menus/detail-update.html'
	def form_valid(self,form):
		obj=form.save(commit=False)
		obj.user=self.request.user
		return super(ItemUpdateView,self).form_valid(form)
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

	def get_context_data(self,*args,**kwargs):
		return super(ItemUpdateView,self).get_context_data(*args,**kwargs)
		context['title']='Update Item'
		return context
	def get_form_kwargs(self):
		kwargs=super(ItemUpdateView,self).get_form_kwargs()
		kwargs['user']=self.request.user
		return kwargs


# Create your views here.

menus/templates/menus/detail-update.html
{% extends 'base.html' %}
{%block title %} Menu Items |{{ block.super }}{%endblock%}

{% block content %}
<h1> {{form.instance.name}}</h1>
Location: {{form.instance.restaurants.name}}<br/>
{% if form.instance.contents %}
Contents
<ul>
    {% for item in form.instance.get_contents %}
    <li>{{item}}</li>

    {%endfor%}
</ul>
{% endif %}
{% if form.instance.excludes %}
Excludes
<ul>
	{% for item in form.instance.get_excludes %}
	<li>{{item}}</li>
	{%endfor%}
</ul>
{%endif%}
<hr/>
<h3> Make Changes </h3>
{% include 'snippets/form-snippet.html' with form=form %}
{% endblock %}

menus/templates/menus/home-feed.html
{% extends 'base.html' %}
{% block css %}
<style>
.card{
	border-top: 2px solid black;
}
</style>
{% endblock %}
{% block content %}
<div class='row'>

	<h1> User Following Feed </h1>
{% for obj in object_list %}

	<div class="col-12 card mt-3 py-2">
		<h3><b><a href="{% url 'profiles:detail' username=obj.user.username %}">@{{obj.user.username}}</a></b></h3>
		<h4 class="mt-2"><b>{{obj.name}}</b></h4> 
		<p> {{obj.restaurants.title}} | {{obj.restaurants.location}} | {{obj.restaurants.category}}</p>
<p>
	<b class="ml-2">Contains</b>
	
 	{% for ing in obj.get_contents %}
 	<span class="ingredient">{{ing}} </span>
 	{%endfor%}
</p>

</div>

{% endfor %}
</div>
{% endblock %}

menus/templates/menus/item_detail.html
{% extends 'base.html' %}
{%block title %} Menu Items |{{ block.super }}{%endblock%}

{% block content %}
<h1>@{{object.name}}</h1>
Location: {{object.restaurants.name}}<br/>
{% if object.contents %}
Contents
<ul>
    {% for item in object.get_contents %}
    <li>{{item}}</li>

    {%endfor%}
</ul>
{% endif %}
{% if object.excludes %}
Excludes
<ul>
	{% for item in object.get_excludes %}
	<li>{{item}}</li>
	{%endfor%}
</ul>
{%endif%}
{% endblock %}

menus/templates/menus/item_list.html
{% extends 'base.html' %}
{%block title %}Menus |{{ block.super }}{%endblock%}

{% block content %}
<h1> Menus<small><a href="{% url 'menus:create' %}">Add</a></small></h1>
<ul>
{% for object in object_list %}
<li><a href="{{ object.get_absolute_url }}">{{object.name}}</a><br/>
{% if object.contents %}
Contents
<ul>
    {% for item in object.get_contents %}
    <li>{{item}}</li>

    {%endfor%}
</ul>
{% endif %}
{% if object.excludes %}
Excludes
<ul>
	{% for item in object.get_excludes %}
	<li>{{item}}</li>
	{%endfor%}
</ul>
{%endif%}
</li>
{% empty %}
<a href="{% url 'menus:create' %}">Add One</a>

{% endfor %}
</ul>
{% endblock %}