menus/urls.py
from django.conf.urls import url
from .views import(
	ItemListView,
	ItemDetailView,
	ItemCreateView,
	ItemUpdateView,

)

urlpatterns= [

url(r'^create/$', ItemCreateView.as_view(),name='create'),
#url(r'^(?P<pk>\d+)/edit/$',ItemUpdateView.as_view(),name='update'),
url(r'^(?P<pk>\d+)/$',ItemUpdateView.as_view(),name='detail'),
url(r'^$',ItemListView.as_view(),name='list'),



]

muipicky/urls.py
from django.conf.urls import url,include
from profiles.views import ProfileToggle,RegisterView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import views as auth_views
from menus.views import HomeView
from django.contrib import admin
from restaurants.views import RestaurantList,RestaurantCreateView,RestaurantUpdateView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(),name='home'),
    url(r'^About/$', TemplateView.as_view(template_name='About.html'),name='about'),
    url(r'^restaurants/$',RestaurantList.as_view(),name='restaurants'),
    url(r'^items/',include('menus.urls',namespace='menus')),
    url(r'^u/',include('profiles.urls',namespace='profiles')),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^profile-follow/$',ProfileToggle.as_view(),name='follow'),
    url(r'^password-reset/$', auth_views.password_reset,name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done,name='password_reset_done'),
    url(r'^password-reset/complete/$',auth_views.password_reset_complete,name='password_reset_complete'),
    url(r'^password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$',auth_views.password_reset_confirm,name='password_reset_confirm'),
    url(r'^restaurants/create/$', RestaurantCreateView.as_view(),name='restaurants-create'),
    url(r'^restaurants/(?P<slug>[\w-]+)/$',RestaurantUpdateView.as_view(),name='detail'),
    #url(r'^restaurants/(?P<slug>[\w-]+)/edit/$',RestaurantUpdateView.as_view(),name='edit'),
  #  url(r'^restaurants/moga/$',MogaRestaurants.as_view()),
    url(r'^Contact/$', TemplateView.as_view(template_name='Contact.html'),name='contact'),
]

profiles/urls.py
from .views import ProfileItemView,ShowView
from django.conf.urls import url

urlpatterns=[

url(r'^users/$',ShowView.as_view(),name='users'),
url(r'^(?P<username>[\w-]+)/$', ProfileItemView.as_view(),name='detail'),


]

templates/About.html
{% extends "base.html" %}
{% block title %}About ||{{ block.super }}{% endblock title %}
{% block content %}
		<h1>About </h1>
<h1> Dainty Diet </h1>
<p>
	This is a food picky application. Really Useful when its difficult to choose which location to dine out.
	Add your favorite Restaurants alongwith the Menu Items.
	
</p>
{% endblock %}
	

templates/Contact.html
{% extends "base.html" %}
{% block title %}Contact ||{{ block.super }}{% endblock title %}
{%block content %}
		<h1>Contact</h1>

<p>
	Aakanksha Tewari
	8360767199
</p>

{% endblock content %}
		
	

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<title>{% block title %}Dainty Diet.com{% endblock title %}</title>
		{% include 'snippets/css.html' %}
		<link rel="stylesheet" href="{% static 'index.css' %}">
		<style>

		body{
			
		}
		a{
			color: inherit;
			text-decoration: none;
		}
		a:hover{
			text-decoration: none;
		}
		nav{
    display: flex;
    align-items: center;
    height: 7.5vh;
    position: fixed;
    box-shadow: 0 0 1em black;
    background-color: pink;
    /* color: white; */
	border-bottom: 0.25em solid #412234;
	padding: 0 2%;

}
nav ul{
    height: 75%;
    display: flex;
    align-items: center;
    list-style: none;
	padding: 0;
	margin: 0;
    margin-left: 25px;
}
nav ul li{
	height: 100%;
}
nav ul a{
    height: 100%;
    padding: 0 2vw;
    margin-right: 12px; 
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s ease-in-out;
    opacity: 0.75;
    border-radius: 8px;
}
nav ul a:hover{
    opacity: 1;
    background-color: #0e2ddd;
    color: white;
}
.navbar-brand{
	font-size: 1.25em;
	text-align: center;
}
.navbar-brand:hover{
    /* font-size: 120%; */
}
.ml-auto{
	margin-left: auto;
}
.muted{
	opacity: 0.75;
	font-size: 0.75em;
}


.button{
    position: relative;
    padding: 12px 0;
    margin-right: 12px;
    overflow: hidden;
	border-radius: 0;
	background-color: transparent;
}
.fill{
    position: absolute;
    top: 100%;
    width: 100%;
    height: 0;
    transition: all 0.2s ease;
    z-index: 0;
}
.button-text{
    position: relative;
    padding: 0 24px;
    z-index: 2;
}
.button:hover .button-text{
    color: white;
}
.primary-button{
    border: 2px solid #0e34a0;
    color: #0e34a0;
}
.primary-button .fill{
    background-color: #0e34a0;
}
.danger-button{
    color: red;
    background-color: white;
    border: 2px solid red;
}
.danger-button .fill{
    background-color: red;
}
.success-button{
    color: #1b5e20;
    border: 2px solid #1b5e20;
}
.success-button .fill{
    background-color: #1b5e20;
}
.secondary-button{
    padding: 6px 0;
    margin-right: 12px;
}
.button:hover .fill{
    top: 0;
    height: 100%;
}
.ingredient{
	margin-left: 12px;
	border: 2px solid #1b5e20;
	padding: 6px 6px;
}
.card{
    transition:all 0.25s ease-in-out;
}
.card:hover{
    box-shadow: 0 3px 16px black;
}
		
		</style>
		{% block css %}
		{% endblock %}
	</head>
	
	<body>
		
		<nav class="navbar">
			<a href="{% url 'home' %}" class="navbar-brand">Dainty Diet</a>
			<ul>
				<li><a href="{% url 'about' %}">About</a></li>
				<li><a href="{% url 'contact' %}">Contact</a></li>
				<li><a href="{% url 'profiles:users' %}">Users</a></li>
			</ul>
			<ul class="ml-auto">
			{% if request.user.is_authenticated %}
			<li><a href="{% url 'restaurants' %}">Restaurants</a></li>
			<li><a href="{% url 'logout' %}">LogOut</a></li>
			<li><a href="{% url 'menus:list' %}">Menu</a></li>
			{% else %}
			<li><a href="{% url 'login' %}">Login</a></li>
			<li><a href="{% url 'register' %}">Register</a></li>
			{% endif %}
			</ul>
		</nav>
	<div class="container" style="margin-top: 2.5vh;">
		{% block content %}
		{% endblock content %}
	</div>
	{% include 'snippets/js.html' %}
	</body>
</html>

templates/form.html
{% extends 'base.html' %}
{%block title %} {{title}}  |{{ block.super }}{%endblock%}

{% block content %}
<h1>{{title}}</h1>
{% include 'snippets/form-snippet.html' %}
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}Welcome || {{ block.super }}{% endblock title %}
{% block content %}
<h1>Welcome to Dainty Diet</h1>
	<a href="{% url 'register'%}">New Here? Register</a><br/>
	<a href="{% url 'login' %}">Already Registered? Login </a>
		
{% endblock content %}